package GUI;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class Menu extends javax.swing.JFrame {
        private DefaultTableModel model = null;
        private PreparedStatement stat;
        private ResultSet rs;
        Koneksi_Database k = new Koneksi_Database();
    
    /**
     * Creates new form Menu
     */
        
    cMenu menus[];
    int idMenu, jmlhMenu, maksmmenu;
    double hrgMenu,stokMenu=0;
    
    public Menu() {
        menus = new cMenu[5];
        initComponents();
    }
    
    class tabel_menu extends Menu {
        int id_menu, harga_menu, stok_menu;
        String nama_menu;
        
        public tabel_menu () {
            this.id_menu = Integer.parseInt(txtIDMenu.getText());
            this.nama_menu = txtNamaMenu.getText();
            this.harga_menu = Integer.parseInt(txtHarga.getText());
            this.stok_menu = Integer.parseInt(txtStok.getText());
        }
    }
    
    public void refreshTable () {
        model = new DefaultTableModel();
        model.addColumn("id_menu");
        model.addColumn("nama_menu");
        model.addColumn("harga_menu");
        model.addColumn("stock_menu");
        table_menu.setModel(model);
        
        try {
            this.stat = k.getCon().prepareStatement("select * from tabel_menu");
            this.rs = this.stat.executeQuery();
            
            while (rs.next()) {
                Object[] data = {
                   rs.getInt("id_menu"), 
                   rs.getString ("nama_menu"),
                   rs.getInt("harga_menu"),
                   rs.getInt("stock_menu")
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtIDMenu.setText("");
        txtNamaMenu.setText("");
        txtHarga.setText("");
        txtStok.setText("");
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDMenu = new javax.swing.JTextField();
        txtNamaMenu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_menu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(119, 136, 153));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Menu");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(110, 10, 221, 37);

        jButton6.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        jButton6.setText("BACK");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(380, 10, 65, 37);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 470, 60);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("ID Menu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 107, 28);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Nama Menu");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 71, 31);

        txtIDMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMenuActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDMenu);
        txtIDMenu.setBounds(131, 71, 313, 31);

        txtNamaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMenuActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaMenu);
        txtNamaMenu.setBounds(130, 110, 313, 31);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel6.setText("Harga");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 150, 52, 32);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel7.setText("Stok");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 190, 50, 38);

        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });
        jPanel1.add(txtStok);
        txtStok.setBounds(130, 190, 312, 31);

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga);
        txtHarga.setBounds(130, 150, 313, 31);

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(190, 260, 93, 40);

        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel1.add(btn_input);
        btn_input.setBounds(70, 260, 98, 40);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(300, 260, 93, 40);

        table_menu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        table_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Menu", "Nama Menu", "Harga", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_menu);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 320, 452, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(486, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtIDMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMenuActionPerformed

    private void txtNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here: 
            boolean ketemu = false;
            int indeks = 0;
            String km = JOptionPane.showInputDialog(this, "Masukkan ID Menu");
            for (int i = 0; i < jmlhMenu; i++) {
                indeks=i;
                if(menus[i].getkodeMenu().equalsIgnoreCase(km)){
                    ketemu = true;
                    break;
                }
            }
            if(ketemu==true){
                int hm = Integer.parseInt(JOptionPane.showInputDialog(this, "Masukkan Harga Baru"));
                int j = JOptionPane.showConfirmDialog(this, "Yakin diubah?");
                if(j==0){
                    menus[indeks].sethrgMenu(hm);
                    
                    DefaultTableModel model = (DefaultTableModel)table_menu.getModel();
                    model.setValueAt(hm, indeks, 2);
                    JOptionPane.showMessageDialog(this, "Berhasil Diupdate");
                }else{
                    JOptionPane.showMessageDialog(this, "Batal Diupdate!!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID Tidak Tersedia");
            }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_menu.getModel();
        
        if(jmlhMenu<5){
            boolean ketemu = false;
            for (int i = 0; i < jmlhMenu; i++) {
                if(menus[i].getkodeMenu().equalsIgnoreCase(txtIDMenu.getText())){
                    ketemu = true;
                    break;
                }
            }
            if(ketemu==true){
                JOptionPane.showMessageDialog(this, "Menu sudah ada");
            }else{
                String km = txtIDMenu.getText();
                String nm = txtNamaMenu.getText();
                int hm = Integer.parseInt(txtHarga.getText());
                int sm = Integer.parseInt(txtStok.getText());
                menus[jmlhMenu] = new cMenu(km, nm, hm, sm);

                // Tambahkan baris ke dalam tabel
                model.addRow(new Object[]{km, nm, hm, sm});
                jmlhMenu++;
                
            }
            }else{
            JOptionPane.showMessageDialog(this, "Kapasitas Menu sudah full");
            // Kosongkan kembali JTextField
            txtIDMenu.setText("");
            txtNamaMenu.setText("");
            txtStok.setText("");
            txtHarga.setText("");
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        boolean ketemu = false;
            int indekshapus = 0;
            String km = JOptionPane.showInputDialog(this, "Masukkan ID Menu");
            for (int i = 0; i < jmlhMenu; i++) {
                indekshapus=i;
                if(menus[i].getkodeMenu().equals(km)){
                    ketemu = true;
                    break;
                }
            }
            if(ketemu==true){
                int j = JOptionPane.showConfirmDialog(this, "Yakin diubah?");
                if(j==0){
                    for (int i = indekshapus; i < jmlhMenu; i++) {
                        if(i==jmlhMenu-1)
                            menus[i]=null;
                        else
                            menus[i]=menus[i+1];
                    }
                    jmlhMenu--;
                    //update table
                    DefaultTableModel model = (DefaultTableModel)table_menu.getModel();
                    //dihapus ketika objek ditemukan
                    model.removeRow(indekshapus);
                    JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
                }else{
                    JOptionPane.showMessageDialog(this, "Batal Dihapus!!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID Tidak Tersedia");
            }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_input;
    public javax.swing.JButton btn_update;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_menu;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDMenu;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
