/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import GUI.cPelanggan;
import GUI.Home;
import GUI.Home;
import GUI.Koneksi_Database;
import GUI.Menu;
import GUI.cMenu;

import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class Transaksi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi_Database k = new Koneksi_Database();
    Menu update = new Menu();
    private JTextField txtIDPel;
    
    
    
    
    cPelanggan p=null;
    cPelanggan pel[];
    int IDPel;
    int jmlhPel;//indeks array
    int maksmPel;//batas array
    
    cTransaksi t=null;
    cTransaksi trx[];
    double totalbiaya,kembalian;
    int jmlhTrx,maksmTrx;
    
    cMenu m = null;
    cMenu menus[];
    int jmlhMenu;//indeks array
    int maksmMenu;//batas array
    double hrgMenu,stokMenu=0;
    /**
     * Creates new form transaksi
     */
    public Transaksi () {
        
        int idTransaksi,idMenu;
        String namaPelanggan, tanggal, namaMenu, keterangan;
        trx = new cTransaksi[5];
        jmlhTrx = 0; maksmTrx = 5;
        menus = new cMenu[5];
        jmlhMenu=0;maksmMenu=5;
        pel = new cPelanggan[5];
        jmlhPel=0;maksmPel=5;
        
        initComponents();
        
    }

    private static class id_transaksi {
          public id_transaksi() {
              
        }
    }   
    
    public void totalBiaya(){
        int jumlahBaris = table_transaksi.getRowCount();
        int totalBiaya = 0;
        int jumlahMenu,hargaMenu;
        for (int i = 0; i < jumlahBaris; i++) {
            hargaMenu = Integer.parseInt(txtHarga.getText());
            jumlahMenu = Integer.parseInt(txtJumlah.getText());
            totalBiaya += jumlahMenu * hargaMenu;
        }
        txBayar.setText(String.valueOf(totalBiaya));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txNamaPlg1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnbck = new javax.swing.JButton();
        Harga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDTrx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IDTransaksi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_transaksi = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        IDPelanggan = new javax.swing.JLabel();
        txBayar = new javax.swing.JTextField();
        txKembalian = new javax.swing.JTextField();
        TotalBayar = new javax.swing.JLabel();
        Bayar = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txIDmenu = new javax.swing.JTextField();
        txNamaPlg = new javax.swing.JTextField();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtIDPlg = new javax.swing.JTextField();
        txtIDMenu = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();

        txNamaPlg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaPlg1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(119, 136, 153));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(110, 10, 221, 37);

        jbtnbck.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        jbtnbck.setText("BACK");
        jbtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnbck);
        jbtnbck.setBounds(380, 10, 65, 37);

        Harga.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Harga.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal");

        txtIDTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDTrxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("ID Makanan");

        IDTransaksi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        IDTransaksi.setText("ID Transaksi");

        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "ID Pelanggan", "ID Makanan", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_transaksi);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        IDPelanggan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        IDPelanggan.setText("ID Pelanggan");

        txBayar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBayarActionPerformed(evt);
            }
        });

        txKembalian.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txKembalian.setEnabled(false);
        txKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKembalianActionPerformed(evt);
            }
        });

        TotalBayar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        TotalBayar.setText("Total Bayar");

        Bayar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Bayar.setText("Bayar");

        Kembalian.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Kembalian.setText("Kembalian");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Jumlah");

        txIDmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDmenuActionPerformed(evt);
            }
        });

        txNamaPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaPlgActionPerformed(evt);
            }
        });

        txtIDPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPlgActionPerformed(evt);
            }
        });

        txtIDMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMenuActionPerformed(evt);
            }
        });

        txtTotalBayar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtTotalBayar.setEnabled(false);
        txtTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBayarActionPerformed(evt);
            }
        });

        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txNamaPlg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIDTrx, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                        .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Harga)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel5)
                                        .addComponent(IDPelanggan)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                .addComponent(txtIDPlg)
                                                .addComponent(txtIDMenu)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(16, 16, 16)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txIDmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNamaPlg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDPlg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txIDmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIDMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalBayar)
                    .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembalian)
                    .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        setSize(new java.awt.Dimension(483, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jbtnbckActionPerformed

    private void txIDmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDmenuActionPerformed

    private void txNamaPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaPlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaPlgActionPerformed

    private void txtIDTrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDTrxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDTrxActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        boolean ketemu = false;
            int indekshapus = 0;
            String IDTrx = JOptionPane.showInputDialog(this, "Masukkan ID Transaksi");
            for (int i = 0; i < jmlhMenu; i++) {
                indekshapus=i;
                if(trx[i].getIdTransaksi().equals(IDTrx)){
                    ketemu = true;
                    break;
                }
            }
            if(ketemu==true){
                int j = JOptionPane.showConfirmDialog(this, "Yakin dihapus?");
                if(j==0){
                    for (int i = indekshapus; i < jmlhMenu; i++) {
                        if(i==jmlhMenu-1)
                            menus[i]=null;
                        else
                            menus[i]=menus[i+1];
                    }
                    jmlhMenu--;
                    //update table
                    DefaultTableModel model = (DefaultTableModel)table_transaksi.getModel();
                    //dihapus ketika objek ditemukan
                    model.removeRow(indekshapus);
                    JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
                }else{
                    JOptionPane.showMessageDialog(this, "Batal Dihapus!!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID Tidak Tersedia");
            }
    }//GEN-LAST:event_btn_deleteActionPerformed

    // INPUT 
    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        double hrgMenu, totalbiaya;
        int jmlTrx;
        
        hrgMenu = Double.parseDouble(txtHarga.getText());
        jmlTrx = Integer.parseInt(txtJumlah.getText());
        
        totalbiaya = (hrgMenu * jmlTrx);
        txtTotalBayar.setText(""+totalbiaya);
        
        DefaultTableModel model = (DefaultTableModel) table_transaksi.getModel();
        
        if(jmlhMenu<5){
            boolean ketemu = false;
            for (int i = 0; i < jmlhMenu; i++) {
                if(trx[i].getIdTransaksi().equalsIgnoreCase(txtIDTrx.getText())){
                    ketemu = true;
                    break;
                }
            }
            if(ketemu==true){
                JOptionPane.showMessageDialog(this, "ID sudah ada");
            }else{
                String IDTrx = txtIDTrx.getText();
                String IDPel = txtIDPlg.getText();
                String km = txtIDMenu.getText();
                int jumlah = Integer.parseInt(txtJumlah.getText());
                int totalsementara = jumlah * Integer.parseInt(txtHarga.getText());
                trx[jmlhMenu] = new cTransaksi();

                // Tambahkan baris ke dalam tabel
                model.addRow(new Object[]{IDTrx, IDPel, km, jumlah, totalsementara});
                jmlhMenu++;
                
            }
            }else{
            JOptionPane.showMessageDialog(this, "Kapasitas Transaksi sudah full");
            
            int totalHarga=0;
            for (int i = 0; i < table_transaksi.getRowCount(); i++) {
                totalHarga += Integer.parseInt(table_transaksi.getValueAt(i, 4).toString().substring(4));
            }
            txtTotalBayar.setText(""+totalHarga);
            
            
            // Kosongkan kembali JTextField
            txtIDTrx.setText("");
            txtIDPlg.setText("");
            txtIDMenu.setText("");
            txtJumlah.setText("");
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    // UPDATE
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        boolean ketemu = false;
            int indeks = 0;
            String IDTrx = JOptionPane.showInputDialog(this, "Masukkan ID Transaksi");
            for (int i = 0; i < jmlhMenu; i++) {
                indeks=i;
                if(trx[i].getIdTransaksi().equalsIgnoreCase(IDTrx)){
                    ketemu = true;
                    break;
                }
            }
            if(ketemu==true){
                String hm = JOptionPane.showInputDialog(this, "Masukkan ID Menu Baru");
                int j = JOptionPane.showConfirmDialog(this, "Yakin diubah?");
                if(j==0){
                    menus[indeks].setkodeMenu(hm);
                    
                    DefaultTableModel model = (DefaultTableModel)table_transaksi.getModel();
                    model.setValueAt(hm, indeks, 2);
                    JOptionPane.showMessageDialog(this, "Berhasil Diupdate");
                }else{
                    JOptionPane.showMessageDialog(this, "Batal Diupdate!!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID Tidak Tersedia");
            }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void table_transaksiMouseClicked (java.awt.event.MouseEvent evt) {
    }
    
    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txKembalianActionPerformed

    private void txBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBayarActionPerformed

    private void txNamaPlg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaPlg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaPlg1ActionPerformed

    private void txtIDPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPlgActionPerformed

    private void txtIDMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMenuActionPerformed

    private void txtTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBayarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTotalBayarActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        double totalbayar, uangBayar, uangKembalian;
        
        totalbayar = Double.parseDouble(txtTotalBayar.getText());
        uangBayar = Double.parseDouble(txBayar.getText());
        
        
        if (uangBayar > totalbayar) {
            uangKembalian = uangBayar - totalbayar;
            txKembalian.setText(""+uangKembalian);
        } else {
            txKembalian.setText("uang anda tidak cukup!");
        }
                
        
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bayar;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel IDPelanggan;
    private javax.swing.JLabel IDTransaksi;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JLabel TotalBayar;
    private javax.swing.JButton btnBayar;
    public javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_input;
    public javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtnbck;
    private javax.swing.JTable table_transaksi;
    private javax.swing.JTextField txBayar;
    private javax.swing.JTextField txIDmenu;
    private javax.swing.JTextField txKembalian;
    private javax.swing.JTextField txNamaPlg;
    private javax.swing.JTextField txNamaPlg1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDMenu;
    private javax.swing.JTextField txtIDPlg;
    private javax.swing.JTextField txtIDTrx;
    private javax.swing.JTextField txtJumlah;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
